### ISSUE TITLE
Implement Connection Stuff

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/core#13]
Every GraphQL query is implemented except for:

* Playlist.items
* Query.songs
* Query.albums
* Query.artists
* Query.playlists

These are similar. Once one is done, the rest should be pretty easy.

**Comment by 0xcaff** [comment]
Handling pagination is a bit difficult because results can be ordered in many different ways. [This website](https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/) outlines some ways:

1. Limit-Offset. This is easy to implement for all orderings. It is also the most inefficient. It might still be fast enough. We could go with this then fix if needed.

2. Cursors. Requires all requests to be handled by a single server (not an issue). Not supported by SQLite.

3. Keyset Pagination. I don't completely understand how this works. The ORM might have issues with creating an index. This should be investigated more.

Getting the number of elements in a table is expensive and `count` should probably be fetched lazily.

**Comment by 0xcaff** [comment]
I've been working on implementing 1 in https://github.com/forte-music/core/tree/feature/connections

Everything works except for the ordering. It currently fails to compile. https://github.com/forte-music/core/blob/4683e124e41b188a180126a32d5ac1c27a3f72cc/src/models/query.rs#L32-L41

Since each branch of the match has a different return type (caused by diesel's type safety), the query might have to be made in the match arms.

**Comment by 0xcaff** [comment]
This code could maybe be cleaned up with boxed queries. http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed

**Comment by 0xcaff** [comment]
I still haven't found a way to get this to compile. I'm pretty sure the issue is the return type of `Self::table` isn't a concrete type on which the `::Output` associated type can be resolved. The only way might be to box the table or something.

@Mcat12 Is this even possible?

**Comment by Mcat12** [comment]
In terms of not having a concrete return type, `impl Trait` or just boxing would be the solution.
