### ISSUE TITLE
Use error_chain

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/core#16]
It adds backtraces. https://docs.rs/error-chain/0.11.0/error_chain/

**Comment by 0xcaff** [comment]
It's used a bit in https://github.com/forte-music/core/tree/tests/fixture

**Comment by ebkalderon** [comment]
Perhaps it might be better to use [`failure`](https://docs.rs/failure/0.1.1/failure/) instead of `error_chain` these days? It's created by many of the same developers incorporating lessons they learned while creating `error_chain`, and many crates are increasingly switching over.

**Comment by 0xcaff** [comment]
@ebkalderon Thanks for the suggestion and for checking out our project!

@Mcat12 suggested this also. I ended up going with `error_chain` because I didn't completely understand how `failure` worked with other custom errors. `error_chain` had better documentation too.

For the record, most usages of `Box<Error>` and `impl Error` are gone. There's one left in `server/bin.rs`.
