### ISSUE TITLE
CI Performance

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/core#27]
Builds take like 6m.

![image](https://user-images.githubusercontent.com/3277097/40529344-560fb02e-5fc2-11e8-9b28-92ca7174833d.png)

The main culprits seem to be the workspace and cache. The workspace and cache persist the same things, they just update at different times. Workspaces should probably go because they are always restored at the beginning of a build. The cache should probably be updated on every build or there should be multiple caches.

**Comment by Mcat12** [comment]
The cache won't update if code changes, but the workspace does update. Without the workspace updating, the next test step won't be using the most recent binary.

I think we should minimize workspace to only store the final binaries.

**Comment by 0xcaff** [comment]
That would work if cargo doesn't recompile when intermediate assets are missing. Need to investigate this more.
