### ISSUE TITLE
Switch to Actix

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/core#37]
Iron is awesome, but it is dead. :sob: Let's switch to actix for the time being so things like #21  and #9 work. Also, async rust is the future.

**Comment by 0xcaff** [comment]
Got the graphql and graphiql endpoints working! 
![image](https://user-images.githubusercontent.com/3277097/40593356-0e0e9548-61f6-11e8-9478-520bdcf41a22.png)

**Comment by Mcat12** [comment]
Nice! I was having issues with database context.
